name: Test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/stefan-hoeck/idris2-pack:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Type checking
        run: |
          pack typecheck pbt
      - name: Testing
        run: |
          pack test pbt


